export default [
  {
    id: 1,
    name: "Aviator Sunglasses",
    category: "Glasses",
    price: 79.99,
    size: ["One Size"],
    color: "Gold",
    material: "Metal",
    stock: 50,
    imageUrl: "/glasses/aviator-sunglasses.jpg",
  },
  {
    id: 2,
    name: "Round Vintage Glasses",
    category: "Glasses",
    price: 49.99,
    size: ["One Size"],
    color: "Black",
    material: "Metal",
    stock: 40,
    imageUrl: "/glasses/round-vintage-glasses.jpg",
  },
  {
    id: 3,
    name: "Cat-Eye Sunglasses",
    category: "Glasses",
    price: 59.99,
    size: ["One Size"],
    color: "Pink",
    material: "Plastic",
    stock: 30,
    imageUrl: "/glasses/cat-eye-sunglasses.jpg",
  },
  {
    id: 4,
    name: "Rectangular Blue Light Glasses",
    category: "Glasses",
    price: 29.99,
    size: ["One Size"],
    color: "Blue",
    material: "Plastic",
    stock: 70,
    imageUrl: "/glasses/rectangular-blue-light-glasses.jpg",
  },
  {
    id: 5,
    name: "Oversized Sunglasses",
    category: "Glasses",
    price: 69.99,
    size: ["One Size"],
    color: "Black",
    material: "Plastic",
    stock: 45,
    imageUrl: "/glasses/oversized-sunglasses.jpg",
  },
  {
    id: 6,
    name: "Classic Wayfarer Sunglasses",
    category: "Glasses",
    price: 39.99,
    size: ["One Size"],
    color: "Black",
    material: "Plastic",
    stock: 55,
    imageUrl: "/glasses/classic-wayfarer-sunglasses.jpg",
  },
  {
    id: 7,
    name: "Metal Frame Glasses",
    category: "Glasses",
    price: 89.99,
    size: ["One Size"],
    color: "Silver",
    material: "Metal",
    stock: 25,
    imageUrl: "/glasses/metal-frame-glasses.jpg",
  },
  {
    id: 8,
    name: "Transparent Clear Glasses",
    category: "Glasses",
    price: 19.99,
    size: ["One Size"],
    color: "Clear",
    material: "Plastic",
    stock: 60,
    imageUrl: "/glasses/transparent-clear-glasses.jpg",
  },
  {
    id: 9,
    name: "Polarized Sport Sunglasses",
    category: "Glasses",
    price: 59.99,
    size: ["One Size"],
    color: "Black",
    material: "Polycarbonate",
    stock: 35,
    imageUrl: "/glasses/polarized-sport-sunglasses.jpg",
  },
  {
    id: 10,
    name: "Square Sunglasses",
    category: "Glasses",
    price: 49.99,
    size: ["One Size"],
    color: "Brown",
    material: "Plastic",
    stock: 40,
    imageUrl: "/glasses/square-sunglasses.jpg",
  },
  {
    id: 11,
    name: "Mirrored Aviator Sunglasses",
    category: "Glasses",
    price: 89.99,
    size: ["One Size"],
    color: "Silver",
    material: "Metal",
    stock: 25,
    imageUrl: "/glasses/mirrored-aviator-sunglasses.jpg",
  },
  {
    id: 12,
    name: "Round Lennon Sunglasses",
    category: "Glasses",
    price: 34.99,
    size: ["One Size"],
    color: "Gold",
    material: "Metal",
    stock: 50,
    imageUrl: "/glasses/round-lennon-sunglasses.jpg",
  },
  {
    id: 13,
    name: "Wayfarer Blue Light Glasses",
    category: "Glasses",
    price: 29.99,
    size: ["One Size"],
    color: "Tortoise",
    material: "Plastic",
    stock: 55,
    imageUrl: "/glasses/wayfarer-blue-light-glasses.jpg",
  },
  {
    id: 14,
    name: "Wrap Around Sunglasses",
    category: "Glasses",
    price: 69.99,
    size: ["One Size"],
    color: "Gray",
    material: "Polycarbonate",
    stock: 40,
    imageUrl: "/glasses/wrap-around-sunglasses.jpg",
  },
  {
    id: 15,
    name: "Retro Round Glasses",
    category: "Glasses",
    price: 24.99,
    size: ["One Size"],
    color: "Black",
    material: "Metal",
    stock: 60,
    imageUrl: "/glasses/retro-round-glasses.jpg",
  },
  {
    id: 16,
    name: "Tortoise Shell Sunglasses",
    category: "Glasses",
    price: 44.99,
    size: ["One Size"],
    color: "Tortoise",
    material: "Plastic",
    stock: 45,
    imageUrl: "/glasses/tortoise-shell-sunglasses.jpg",
  },
  {
    id: 17,
    name: "Black Frame Sunglasses",
    category: "Glasses",
    price: 39.99,
    size: ["One Size"],
    color: "Black",
    material: "Plastic",
    stock: 50,
    imageUrl: "/glasses/black-frame-sunglasses.jpg",
  },
  {
    id: 18,
    name: "Octagonal Sunglasses",
    category: "Glasses",
    price: 79.99,
    size: ["One Size"],
    color: "Gold",
    material: "Metal",
    stock: 20,
    imageUrl: "/glasses/octagonal-sunglasses.jpg",
  },
  {
    id: 19,
    name: "Browline Glasses",
    category: "Glasses",
    price: 34.99,
    size: ["One Size"],
    color: "Black",
    material: "Metal and Plastic",
    stock: 35,
    imageUrl: "/glasses/browline-glasses.jpg",
  },
  {
    id: 20,
    name: "Pilot Style Sunglasses",
    category: "Glasses",
    price: 69.99,
    size: ["One Size"],
    color: "Silver",
    material: "Metal",
    stock: 30,
    imageUrl: "/glasses/pilot-style-sunglasses.jpg",
  },
];
