export default [
  {
    id: 1,
    name: "Classic White T-Shirt",
    category: "Boys",
    price: 19.99,
    size: ["S", "M", "L", "XL"],
    color: "White",
    material: "Cotton",
    stock: 50,
    imageUrl: "/men/classic-white-tshirt.jpg",
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    category: "Boys",
    price: 49.99,
    size: ["30", "32", "34", "36", "38"],
    color: "Blue",
    material: "Denim",
    stock: 30,
    imageUrl: "/men/slim-fit-jeans.jpg",
  },
  {
    id: 3,
    name: "Casual Hoodie",
    category: "Boys",
    price: 39.99,
    size: ["S", "M", "L", "XL"],
    color: "Grey",
    material: "Polyester",
    stock: 20,
    imageUrl: "/men/casual-hoodie.jpg",
  },
  {
    id: 4,
    name: "Chino Pants",
    category: "Boys",
    price: 44.99,
    size: ["30", "32", "34", "36", "38"],
    color: "Khaki",
    material: "Cotton",
    stock: 40,
    imageUrl: "/men/chino-pants.jpg",
  },
  {
    id: 5,
    name: "Polo Shirt",
    category: "Boys",
    price: 29.99,
    size: ["S", "M", "L", "XL"],
    color: "Navy Blue",
    material: "Cotton",
    stock: 35,
    imageUrl: "/men/polo-shirt.jpg",
  },
  {
    id: 6,
    name: "Leather Jacket",
    category: "Boys",
    price: 99.99,
    size: ["M", "L", "XL"],
    color: "Black",
    material: "Leather",
    stock: 15,
    imageUrl: "/men/leather-jacket.jpg",
  },
  {
    id: 7,
    name: "Sweatpants",
    category: "Boys",
    price: 34.99,
    size: ["S", "M", "L", "XL"],
    color: "Dark Grey",
    material: "Cotton Blend",
    stock: 25,
    imageUrl: "/men/sweatpants.jpg",
  },
  {
    id: 8,
    name: "Dress Shirt",
    category: "Boys",
    price: 54.99,
    size: ["S", "M", "L", "XL"],
    color: "White",
    material: "Cotton",
    stock: 18,
    imageUrl: "/men/dress-shirt.jpg",
  },
  {
    id: 9,
    name: "Bomber Jacket",
    category: "Boys",
    price: 79.99,
    size: ["M", "L", "XL"],
    color: "Green",
    material: "Nylon",
    stock: 12,
    imageUrl: "/men/bomber-jacket.jpg",
  },
  {
    id: 10,
    name: "Graphic T-Shirt",
    category: "Boys",
    price: 24.99,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Cotton",
    stock: 45,
    imageUrl: "/men/graphic-tshirt.jpg",
  },
  {
    id: 11,
    name: "Cargo Shorts",
    category: "Boys",
    price: 29.99,
    size: ["S", "M", "L", "XL"],
    color: "Olive",
    material: "Cotton",
    stock: 28,
    imageUrl: "/men/cargo-shorts.jpg",
  },
  {
    id: 12,
    name: "Running Shorts",
    category: "Boys",
    price: 19.99,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Polyester",
    stock: 50,
    imageUrl: "/men/running-shorts.jpg",
  },
  {
    id: 13,
    name: "Denim Jacket",
    category: "Boys",
    price: 59.99,
    size: ["M", "L", "XL"],
    color: "Blue",
    material: "Denim",
    stock: 22,
    imageUrl: "/men/denim-jacket.jpg",
  },
  {
    id: 14,
    name: "V-Neck Sweater",
    category: "Boys",
    price: 34.99,
    size: ["S", "M", "L", "XL"],
    color: "Burgundy",
    material: "Wool Blend",
    stock: 16,
    imageUrl: "/men/v-neck-sweater.jpg",
  },
  {
    id: 15,
    name: "Henley Shirt",
    category: "Boys",
    price: 27.99,
    size: ["S", "M", "L", "XL"],
    color: "Gray",
    material: "Cotton",
    stock: 30,
    imageUrl: "/men/henley-shirt.jpg",
  },
  {
    id: 16,
    name: "Pullover Hoodie",
    category: "Boys",
    price: 44.99,
    size: ["S", "M", "L", "XL"],
    color: "Navy",
    material: "Fleece",
    stock: 20,
    imageUrl: "/men/pullover-hoodie.jpg",
  },
  {
    id: 17,
    name: "Plaid Flannel Shirt",
    category: "Boys",
    price: 32.99,
    size: ["S", "M", "L", "XL"],
    color: "Red",
    material: "Cotton",
    stock: 25,
    imageUrl: "/men/plaid-flannel-shirt.jpg",
  },
  {
    id: 18,
    name: "Men Jeans",
    category: "Boys",
    price: 89.99,
    size: ["8", "9", "10", "11", "12"],
    color: "Brown",
    material: "Leather",
    stock: 15,
    imageUrl: "/men/men-jeans.jpg",
  },
  {
    id: 19,
    name: "Athletic pants",
    category: "Boys",
    price: 39.99,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Polyester Blend",
    stock: 35,
    imageUrl: "/men/athletic-pants.jpg",
  },
  {
    id: 20,
    name: "Trench Coat",
    category: "Boys",
    price: 129.99,
    size: ["M", "L", "XL"],
    color: "Beige",
    material: "Cotton Blend",
    stock: 10,
    imageUrl: "/men/trench-coat.jpg",
  },
];
