export default [
  {
    id: 1,
    name: "Leather Crossbody Bag",
    category: "Purse",
    price: 129.99,
    color: "Brown",
    material: "Leather",
    stock: 30,
    imageUrl: "/purse/leather-crossbody-bag.jpg",
  },
  {
    id: 2,
    name: "Quilted Shoulder Bag",
    category: "Purse",
    price: 99.99,
    color: "Black",
    material: "Synthetic Leather",
    stock: 20,
    imageUrl: "/purse/quilted-shoulder-bag.jpg",
  },
  {
    id: 3,
    name: "Wristlet Clutch",
    category: "Purse",
    price: 49.99,
    color: "Red",
    material: "Suede",
    stock: 40,
    imageUrl: "/purse/wristlet-clutch.jpg",
  },
  {
    id: 4,
    name: "Mini Backpack Purse",
    category: "Purse",
    price: 79.99,
    color: "Blue",
    material: "Nylon",
    stock: 25,
    imageUrl: "/purse/mini-backpack-purse.jpg",
  },
  {
    id: 5,
    name: "Tote Bag",
    category: "Purse",
    price: 139.99,
    color: "Beige",
    material: "Canvas",
    stock: 15,
    imageUrl: "/purse/tote-bag.jpg",
  },
  {
    id: 6,
    name: "Saddle Bag",
    category: "Purse",
    price: 159.99,
    color: "Tan",
    material: "Leather",
    stock: 18,
    imageUrl: "/purse/saddle-bag.jpg",
  },
  {
    id: 7,
    name: "Bucket Bag",
    category: "Purse",
    price: 109.99,
    color: "Olive Green",
    material: "Faux Leather",
    stock: 22,
    imageUrl: "/purse/bucket-bag.jpg",
  },
  {
    id: 8,
    name: "Envelope Clutch",
    category: "Purse",
    price: 54.99,
    color: "Silver",
    material: "Metallic Fabric",
    stock: 35,
    imageUrl: "/purse/envelope-clutch.jpg",
  },
  {
    id: 9,
    name: "Hobo Bag",
    category: "Purse",
    price: 114.99,
    color: "Navy Blue",
    material: "Leather",
    stock: 16,
    imageUrl: "/purse/hobo-bag.jpg",
  },
  {
    id: 10,
    name: "Crossbody Phone Bag",
    category: "Purse",
    price: 39.99,
    color: "Pink",
    material: "Vegan Leather",
    stock: 45,
    imageUrl: "/purse/crossbody-phone-bag.jpg",
  },
  {
    id: 11,
    name: "Chain Strap Purse",
    category: "Purse",
    price: 89.99,
    color: "Gold",
    material: "Metallic Leather",
    stock: 28,
    imageUrl: "/purse/chain-strap-purse.jpg",
  },
  {
    id: 12,
    name: "Box Clutch",
    category: "Purse",
    price: 69.99,
    color: "White",
    material: "Acrylic",
    stock: 33,
    imageUrl: "/purse/box-clutch.jpg",
  },
  {
    id: 13,
    name: "Top Handle Bag",
    category: "Purse",
    price: 149.99,
    color: "Burgundy",
    material: "Leather",
    stock: 14,
    imageUrl: "/purse/top-handle-bag.jpg",
  },
  {
    id: 14,
    name: "Messenger Bag",
    category: "Purse",
    price: 119.99,
    color: "Gray",
    material: "Canvas and Leather",
    stock: 27,
    imageUrl: "/purse/messenger-bag.jpg",
  },
  {
    id: 15,
    name: "Foldover Crossbody Bag",
    category: "Purse",
    price: 99.99,
    color: "Green",
    material: "Polyester",
    stock: 25,
    imageUrl: "/purse/foldover-crossbody-bag.jpg",
  },
  {
    id: 16,
    name: "Barrel Bag",
    category: "Purse",
    price: 134.99,
    color: "Black",
    material: "Leather",
    stock: 20,
    imageUrl: "/purse/barrel-bag.jpg",
  },
  {
    id: 17,
    name: "Flap Bag",
    category: "Purse",
    price: 119.99,
    color: "Coral",
    material: "Faux Leather",
    stock: 22,
    imageUrl: "/purse/flap-bag.jpg",
  },
  {
    id: 18,
    name: "Clutch Purse",
    category: "Purse",
    price: 44.99,
    color: "Champagne",
    material: "Satin",
    stock: 30,
    imageUrl: "/purse/clutch-purse.jpg",
  },
  {
    id: 19,
    name: "Structured Tote Bag",
    category: "Purse",
    price: 159.99,
    color: "Ivory",
    material: "Leather",
    stock: 12,
    imageUrl: "/purse/structured-tote-bag.jpg",
  },
  {
    id: 20,
    name: "Mini Crossbody Bag",
    category: "Purse",
    price: 54.99,
    color: "Lavender",
    material: "Polyurethane",
    stock: 36,
    imageUrl: "/purse/mini-crossbody-bag.jpg",
  },
];
