export default [
  {
    id: 1,
    name: "Running Sneakers",
    category: "Shoes",
    price: 59.99,
    size: [6, 7, 8, 9, 10, 11],
    color: "Gray",
    material: "Mesh",
    stock: 30,
    imageUrl: "/shoes/running-sneakers.jpg",
  },
  {
    id: 2,
    name: "Leather Loafers",
    category: "Shoes",
    price: 79.99,
    size: [7, 8, 9, 10, 11],
    color: "Black",
    material: "Leather",
    stock: 15,
    imageUrl: "/shoes/leather-loafers.jpg",
  },
  {
    id: 3,
    name: "High Heels",
    category: "Shoes",
    price: 49.99,
    size: [5, 6, 7, 8, 9],
    color: "Red",
    material: "Synthetic",
    stock: 20,
    imageUrl: "/shoes/high-heels.jpg",
  },
  {
    id: 4,
    name: "Chelsea Boots",
    category: "Shoes",
    price: 99.99,
    size: [6, 7, 8, 9, 10],
    color: "Brown",
    material: "Leather",
    stock: 18,
    imageUrl: "/shoes/chelsea-boots.jpg",
  },
  {
    id: 5,
    name: "Casual Slip-Ons",
    category: "Shoes",
    price: 29.99,
    size: [6, 7, 8, 9, 10, 11],
    color: "Navy",
    material: "Canvas",
    stock: 40,
    imageUrl: "/shoes/casual-slip-ons.jpg",
  },
  {
    id: 6,
    name: "Ankle Strap Sandals",
    category: "Shoes",
    price: 39.99,
    size: [5, 6, 7, 8, 9],
    color: "Beige",
    material: "Faux Leather",
    stock: 25,
    imageUrl: "/shoes/ankle-strap-sandals.jpg",
  },
  {
    id: 7,
    name: "Hiking Boots",
    category: "Shoes",
    price: 89.99,
    size: [7, 8, 9, 10, 11],
    color: "Olive Green",
    material: "Suede",
    stock: 12,
    imageUrl: "/shoes/hiking-boots.jpg",
  },
  {
    id: 8,
    name: "Flip Flops",
    category: "Shoes",
    price: 14.99,
    size: [5, 6, 7, 8, 9, 10],
    color: "Blue",
    material: "Rubber",
    stock: 50,
    imageUrl: "/shoes/flip-flops.jpg",
  },
  {
    id: 9,
    name: "Platform Sneakers",
    category: "Shoes",
    price: 64.99,
    size: [6, 7, 8, 9],
    color: "White",
    material: "Synthetic",
    stock: 22,
    imageUrl: "/shoes/platform-sneakers.jpg",
  },
  {
    id: 10,
    name: "Oxford Shoes",
    category: "Shoes",
    price: 89.99,
    size: [7, 8, 9, 10, 11],
    color: "Brown",
    material: "Leather",
    stock: 10,
    imageUrl: "/shoes/oxford-shoes.jpg",
  },
  {
    id: 11,
    name: "Espadrilles",
    category: "Shoes",
    price: 34.99,
    size: [5, 6, 7, 8, 9],
    color: "Yellow",
    material: "Canvas",
    stock: 20,
    imageUrl: "/shoes/espadrilles.jpg",
  },
  {
    id: 12,
    name: "Rain Boots",
    category: "Shoes",
    price: 49.99,
    size: [6, 7, 8, 9, 10],
    color: "Green",
    material: "Rubber",
    stock: 18,
    imageUrl: "/shoes/rain-boots.jpg",
  },
  {
    id: 13,
    name: "Wedge Sandals",
    category: "Shoes",
    price: 44.99,
    size: [5, 6, 7, 8, 9],
    color: "Black",
    material: "Synthetic",
    stock: 15,
    imageUrl: "/shoes/wedge-sandals.jpg",
  },
  {
    id: 14,
    name: "Ballet Flats",
    category: "Shoes",
    price: 24.99,
    size: [5, 6, 7, 8, 9],
    color: "Pink",
    material: "Faux Leather",
    stock: 35,
    imageUrl: "/shoes/ballet-flats.jpg",
  },
  {
    id: 15,
    name: "Moccasins",
    category: "Shoes",
    price: 54.99,
    size: [7, 8, 9, 10, 11],
    color: "Tan",
    material: "Leather",
    stock: 12,
    imageUrl: "/shoes/moccasins.jpg",
  },
  {
    id: 16,
    name: "Strappy Heels",
    category: "Shoes",
    price: 69.99,
    size: [5, 6, 7, 8],
    color: "Silver",
    material: "Synthetic",
    stock: 10,
    imageUrl: "/shoes/strappy-heels.jpg",
  },
  {
    id: 17,
    name: "Court Shoes",
    category: "Shoes",
    price: 59.99,
    size: [5, 6, 7, 8, 9],
    color: "Nude",
    material: "Leather",
    stock: 18,
    imageUrl: "/shoes/court-shoes.jpg",
  },
  {
    id: 18,
    name: "Clogs",
    category: "Shoes",
    price: 39.99,
    size: [6, 7, 8, 9],
    color: "Black",
    material: "Synthetic",
    stock: 20,
    imageUrl: "/shoes/clogs.jpg",
  },
  {
    id: 19,
    name: "Slip-Resistant Work Shoes",
    category: "Shoes",
    price: 74.99,
    size: [7, 8, 9, 10, 11],
    color: "Black",
    material: "Rubber",
    stock: 15,
    imageUrl: "/shoes/work-shoes.jpg",
  },
  {
    id: 20,
    name: "Snow Boots",
    category: "Shoes",
    price: 99.99,
    size: [6, 7, 8, 9, 10],
    color: "Gray",
    material: "Nylon",
    stock: 12,
    imageUrl: "/shoes/snow-boots.jpg",
  },
];
