export default [
  {
    id: 1,
    name: "Classic Leather Watch",
    category: "Watches",
    price: 129.99,
    size: ["One Size"],
    color: "Brown",
    material: "Leather",
    stock: 30,
    imageUrl: "/watches/classic-leather-watch.jpg",
  },
  {
    id: 2,
    name: "Sport Chronograph Watch",
    category: "Watches",
    price: 199.99,
    size: ["One Size"],
    color: "Black",
    material: "Rubber",
    stock: 25,
    imageUrl: "/watches/sport-chronograph-watch.jpg",
  },
  {
    id: 3,
    name: "Elegant Gold Watch",
    category: "Watches",
    price: 249.99,
    size: ["One Size"],
    color: "Gold",
    material: "Gold-plated",
    stock: 20,
    imageUrl: "/watches/elegant-gold-watch.jpg",
  },
  {
    id: 4,
    name: "Minimalist Silver Watch",
    category: "Watches",
    price: 99.99,
    size: ["One Size"],
    color: "Silver",
    material: "Stainless Steel",
    stock: 40,
    imageUrl: "/watches/minimalist-silver-watch.jpg",
  },
  {
    id: 5,
    name: "Digital Sports Watch",
    category: "Watches",
    price: 89.99,
    size: ["One Size"],
    color: "Blue",
    material: "Silicone",
    stock: 50,
    imageUrl: "/watches/digital-sports-watch.jpg",
  },
  {
    id: 6,
    name: "Classic Dress Watch",
    category: "Watches",
    price: 159.99,
    size: ["One Size"],
    color: "Black",
    material: "Leather",
    stock: 35,
    imageUrl: "/watches/classic-dress-watch.jpg",
  },
  {
    id: 7,
    name: "Rose Gold Watch",
    category: "Watches",
    price: 179.99,
    size: ["One Size"],
    color: "Rose Gold",
    material: "Stainless Steel",
    stock: 28,
    imageUrl: "/watches/rose-gold-watch.jpg",
  },
  {
    id: 8,
    name: "Luxury Diamond Watch",
    category: "Watches",
    price: 499.99,
    size: ["One Size"],
    color: "Silver",
    material: "Diamond and Stainless Steel",
    stock: 10,
    imageUrl: "/watches/luxury-diamond-watch.jpg",
  },
  {
    id: 9,
    name: "Analog Watch with Leather Strap",
    category: "Watches",
    price: 109.99,
    size: ["One Size"],
    color: "Brown",
    material: "Leather",
    stock: 45,
    imageUrl: "/watches/analog-leather-watch.jpg",
  },
  {
    id: 10,
    name: "Smart Fitness Watch",
    category: "Watches",
    price: 129.99,
    size: ["One Size"],
    color: "Black",
    material: "Silicone",
    stock: 55,
    imageUrl: "/watches/smart-fitness-watch.jpg",
  },
  {
    id: 11,
    name: "Steel Bracelet Watch",
    category: "Watches",
    price: 139.99,
    size: ["One Size"],
    color: "Silver",
    material: "Stainless Steel",
    stock: 38,
    imageUrl: "/watches/steel-bracelet-watch.jpg",
  },
  {
    id: 12,
    name: "Classic Blue Dial Watch",
    category: "Watches",
    price: 119.99,
    size: ["One Size"],
    color: "Blue",
    material: "Leather",
    stock: 30,
    imageUrl: "/watches/blue-dial-watch.jpg",
  },
  {
    id: 13,
    name: "Square Digital Watch",
    category: "Watches",
    price: 59.99,
    size: ["One Size"],
    color: "Black",
    material: "Plastic",
    stock: 60,
    imageUrl: "/watches/square-digital-watch.jpg",
  },
  {
    id: 14,
    name: "Aviator Pilot Watch",
    category: "Watches",
    price: 149.99,
    size: ["One Size"],
    color: "Black",
    material: "Leather",
    stock: 22,
    imageUrl: "/watches/aviator-pilot-watch.jpg",
  },
  {
    id: 15,
    name: "Chronograph Leather Watch",
    category: "Watches",
    price: 199.99,
    size: ["One Size"],
    color: "Brown",
    material: "Leather",
    stock: 27,
    imageUrl: "/watches/chronograph-leather-watch.jpg",
  },
  {
    id: 16,
    name: "Ceramic Watch",
    category: "Watches",
    price: 189.99,
    size: ["One Size"],
    color: "White",
    material: "Ceramic",
    stock: 15,
    imageUrl: "/watches/ceramic-watch.jpg",
  },
  {
    id: 17,
    name: "Vintage Pocket Watch",
    category: "Watches",
    price: 89.99,
    size: ["One Size"],
    color: "Bronze",
    material: "Brass",
    stock: 12,
    imageUrl: "/watches/vintage-pocket-watch.jpg",
  },
  {
    id: 18,
    name: "Modern Slim Watch",
    category: "Watches",
    price: 119.99,
    size: ["One Size"],
    color: "Silver",
    material: "Stainless Steel",
    stock: 32,
    imageUrl: "/watches/modern-slim-watch.jpg",
  },
  {
    id: 19,
    name: "Field Watch",
    category: "Watches",
    price: 79.99,
    size: ["One Size"],
    color: "Green",
    material: "Nylon",
    stock: 25,
    imageUrl: "/watches/field-watch.jpg",
  },
  {
    id: 20,
    name: "Tactical Military Watch",
    category: "Watches",
    price: 99.99,
    size: ["One Size"],
    color: "Black",
    material: "Rubber",
    stock: 18,
    imageUrl: "/watches/tactical-military-watch.jpg",
  },
];
