export default [
  {
    id: 1,
    name: "Floral Print Dress",
    category: "Girls",
    price: 39.99,
    size: ["XS", "S", "M", "L"],
    color: "Multicolor",
    material: "Cotton",
    stock: 25,
    imageUrl: "/women/floral-print-dress.jpg",
  },
  {
    id: 2,
    name: "Skinny Jeans",
    category: "Girls",
    price: 49.99,
    size: ["24", "26", "28", "30", "32"],
    color: "Blue",
    material: "Denim",
    stock: 40,
    imageUrl: "/women/skinny-jeans.jpg",
  },
  {
    id: 3,
    name: "Oversized Cardigan",
    category: "Girls",
    price: 59.99,
    size: ["S", "M", "L"],
    color: "Cream",
    material: "Wool Blend",
    stock: 18,
    imageUrl: "/women/oversized-cardigan.jpg",
  },
  {
    id: 4,
    name: "Pencil Skirt",
    category: "Girls",
    price: 29.99,
    size: ["XS", "S", "M", "L"],
    color: "Black",
    material: "Polyester",
    stock: 20,
    imageUrl: "/women/pencil-skirt.jpg",
  },
  {
    id: 5,
    name: "V-Neck Blouse",
    category: "Girls",
    price: 34.99,
    size: ["XS", "S", "M", "L", "XL"],
    color: "White",
    material: "Silk",
    stock: 30,
    imageUrl: "/women/v-neck-blouse.jpg",
  },
  {
    id: 6,
    name: "Leather Jacket",
    category: "Girls",
    price: 89.99,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Leather",
    stock: 12,
    imageUrl: "/women/leather-jacket.jpg",
  },
  {
    id: 7,
    name: "Maxi Dress",
    category: "Girls",
    price: 54.99,
    size: ["XS", "S", "M", "L"],
    color: "Red",
    material: "Chiffon",
    stock: 15,
    imageUrl: "/women/maxi-dress.jpg",
  },
  {
    id: 8,
    name: "High-Waisted Shorts",
    category: "Girls",
    price: 24.99,
    size: ["XS", "S", "M", "L"],
    color: "Denim Blue",
    material: "Denim",
    stock: 35,
    imageUrl: "/women/high-waisted-shorts.jpg",
  },
  {
    id: 9,
    name: "Peacoat",
    category: "Girls",
    price: 119.99,
    size: ["S", "M", "L"],
    color: "Navy Blue",
    material: "Wool",
    stock: 10,
    imageUrl: "/women/peacoat.jpg",
  },
  {
    id: 10,
    name: "Graphic Tee",
    category: "Girls",
    price: 19.99,
    size: ["XS", "S", "M", "L", "XL"],
    color: "Black",
    material: "Cotton",
    stock: 50,
    imageUrl: "/women/graphic-tee.jpg",
  },
  {
    id: 11,
    name: "Joggers",
    category: "Girls",
    price: 29.99,
    size: ["XS", "S", "M", "L", "XL"],
    color: "Gray",
    material: "Cotton Blend",
    stock: 25,
    imageUrl: "/women/joggers.jpg",
  },
  {
    id: 12,
    name: "Pleated Midi Skirt",
    category: "Girls",
    price: 44.99,
    size: ["XS", "S", "M", "L"],
    color: "Pink",
    material: "Polyester",
    stock: 18,
    imageUrl: "/women/pleated-midi-skirt.jpg",
  },
  {
    id: 13,
    name: "Denim Jacket",
    category: "Girls",
    price: 69.99,
    size: ["S", "M", "L", "XL"],
    color: "Light Blue",
    material: "Denim",
    stock: 28,
    imageUrl: "/women/denim-jacket.jpg",
  },
  {
    id: 14,
    name: "Off-Shoulder Top",
    category: "Girls",
    price: 24.99,
    size: ["XS", "S", "M", "L"],
    color: "White",
    material: "Cotton",
    stock: 22,
    imageUrl: "/women/off-shoulder-top.jpg",
  },
  {
    id: 15,
    name: "Faux Fur Vest",
    category: "Girls",
    price: 49.99,
    size: ["S", "M", "L"],
    color: "Beige",
    material: "Faux Fur",
    stock: 15,
    imageUrl: "/women/faux-fur-vest.jpg",
  },
  {
    id: 16,
    name: "Turtleneck Sweater",
    category: "Girls",
    price: 39.99,
    size: ["S", "M", "L", "XL"],
    color: "Burgundy",
    material: "Wool Blend",
    stock: 18,
    imageUrl: "/women/turtleneck-sweater.jpg",
  },
  {
    id: 17,
    name: "Wide-Leg Trousers",
    category: "Girls",
    price: 59.99,
    size: ["XS", "S", "M", "L"],
    color: "Black",
    material: "Polyester",
    stock: 20,
    imageUrl: "/women/wide-leg-trousers.jpg",
  },
  {
    id: 18,
    name: "Chelsea Pants",
    category: "Girls",
    price: 79.99,
    size: ["6", "7", "8", "9", "10"],
    color: "Brown",
    material: "Leather",
    stock: 12,
    imageUrl: "/women/chelsea-pants.jpg",
  },
  {
    id: 19,
    name: "Blazer",
    category: "Girls",
    price: 99.99,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Polyester",
    stock: 15,
    imageUrl: "/women/blazer.jpg",
  },
  {
    id: 20,
    name: "Bodycon Dress",
    category: "Girls",
    price: 44.99,
    size: ["XS", "S", "M", "L"],
    color: "Green",
    material: "Polyester",
    stock: 20,
    imageUrl: "/women/bodycon-dress.jpg",
  },
];
